# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(625, 565)
        Form.setMinimumSize(QtCore.QSize(625, 565))
        Form.setMaximumSize(QtCore.QSize(625, 565))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 30, 550, 500))
        self.widget.setObjectName("widget")
        self.dub_picture = QtWidgets.QLabel(self.widget)
        self.dub_picture.setGeometry(QtCore.QRect(40, 40, 280, 430))
        self.dub_picture.setStyleSheet("background-image: url(:/images/dubai.JPG);\n"
"border-top-left-radius: 50px;")
        self.dub_picture.setText("")
        self.dub_picture.setObjectName("dub_picture")
        self.background = QtWidgets.QLabel(self.widget)
        self.background.setGeometry(QtCore.QRect(280, 40, 240, 430))
        self.background.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-bottom-right-radius: 50px;")
        self.background.setText("")
        self.background.setObjectName("background")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(340, 70, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.first_name = QtWidgets.QLineEdit(self.widget)
        self.first_name.setGeometry(QtCore.QRect(290, 140, 101, 31))
        self.first_name.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.first_name.setObjectName("first_name")
        self.last_name = QtWidgets.QLineEdit(self.widget)
        self.last_name.setGeometry(QtCore.QRect(400, 140, 101, 31))
        self.last_name.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.last_name.setObjectName("last_name")
        self.email = QtWidgets.QLineEdit(self.widget)
        self.email.setGeometry(QtCore.QRect(290, 190, 211, 31))
        self.email.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.email.setObjectName("email")
        self.password1 = QtWidgets.QLineEdit(self.widget)
        self.password1.setGeometry(QtCore.QRect(290, 240, 211, 31))
        self.password1.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.password1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password1.setObjectName("password1")
        self.password2 = QtWidgets.QLineEdit(self.widget)
        self.password2.setGeometry(QtCore.QRect(290, 290, 211, 31))
        self.password2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.password2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password2.setObjectName("password2")
        self.register_button = QtWidgets.QPushButton(self.widget)
        self.register_button.setGeometry(QtCore.QRect(300, 340, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.register_button.setFont(font)
        self.register_button.setStyleSheet("QPushButton#register_button{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"                            }\n"
"\n"
"QPushButton#register_button:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0  rgba(11, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#register_button:pressed{\n"
"\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"\n"
"}")
        self.register_button.setObjectName("register_button")
        self.register_box = QtWidgets.QLabel(self.widget)
        self.register_box.setGeometry(QtCore.QRect(290, 390, 211, 61))
        self.register_box.setText("")
        self.register_box.setObjectName("register_box")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#0c305e;\">Register</span></p></body></html>"))
        self.first_name.setPlaceholderText(_translate("Form", "First Name"))
        self.last_name.setPlaceholderText(_translate("Form", "Last Name"))
        self.email.setPlaceholderText(_translate("Form", "Email Address"))
        self.password1.setPlaceholderText(_translate("Form", "Create New Password"))
        self.password2.setPlaceholderText(_translate("Form", "Confirm Password"))
        self.register_button.setText(_translate("Form", "Register"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
